drop database if exists EBooksStore;
create database if not exists EBooksStore;
use EBooksStore;
create table if not exists Users(
	userId int primary key auto_increment,
    userAccount varchar(50) not null,
    userPassword varchar(50) not null,
    userName nvarchar(50) not null,
    userEmail varchar(50) not null,
    userIdCardNo varchar(12) not null,
    userBalance decimal(10.2) not null,
    UserShoppingCart bool default false
);

insert into Users(userAccount,userPassword,userName,userEmail,userIdCardNo,userBalance)
values 
('tung','thanh','Nguyễn Thanh Tùng','tung120320@gmail.com','142953173','1000000000'),
('abc','123','ghi','ghi@gmail.com','465785762','2000000'),
('1','1','nga','nga@gmail.com','439540524','500000'),
('tung1','123','dfg','dfg@gmail.com','843755762','1000'),
('hihi','haha','ghgshe','ghgshe@gmail.com','49372898','0');
create table if not exists Orders(
	orderId int(10) primary key auto_increment,
    orderUser int not null,
    orderDate datetime,
    orderStatus int,
    constraint fk_Orders_Users foreign key(orderUser) references Users(userId)
);

create table if not exists Items(
	itemId int primary key auto_increment,
    itemName nvarchar(100) not null,
    itemPrice decimal (10,3) not null,
    itemAuthor nvarchar(50) not null,
    itemCategory nvarchar(50),
    itemDescription text,
    itemISBN int(13),
    itemPublished datetime,
    itemPublisher nvarchar(150),
    itemLanguage varchar(20),
    itemPages int
);
insert into Items(itemName,itemPrice,itemAuthor,itemCategory,itemDescription,itemISBN,itemPublished,itemPublisher,itemLanguage,itemPages)
values
('Learning Bootstrap 4 by Building Projects','700000','Eduonix Learning Solutions','Bootstrap','Bootstrap, the world`s most popular frontend framework, is an open By the end of this book, you will have built websites that are visually appealing, responsive, the open By the end of this book, you will have built websites that are visually appealing, responsive, the open By the end of this book, you will have built websites that are visually appealing, responsive, the open By the end of this book, you will have built websites that are visually appealing, responsive, the open By the end of this book, you will have built websites that are visually appealing, responsive, the open By the end of this book, you will have built websites that are visually appealing, responsive, the open By the end of this book, you will have built websites that are visually appealing, responsive, the world`s most popular frontend framework, is an open By the end of this book, you will have built websites that are visually appealing, responsive,appealing, responsive, and robust.','178934325','2018-04-03','Packt Publishing','English','218'),
('Machine Learning and AI for Healthcare','649000','Arjun Panesar','Big Data','Explore the theory and practical applications of artificial intelligence (AI) and machine learning in healthcare. This book offers a guided tour of machine learning algorithms, architecture design, and applications of learning in healthcare and big data challenges.You`ll discover the ethical implications of healthcare data analytics and the future of AI in population and patient health optimization. You`ll also create a machine learning model, evaluate performance and operationalize its outcomes within your organization. Machine Learning and AI for Healthcare provides techniques on how to apply machine learning within your organization and evaluate the efficacy, suitability, and efficiency of AI applications. These are illustrated through leading case studies, including how chronic disease is being redefined through patient-led data learning and the Internet of Things. Gain a deeper understanding of key machine learning algorithms and their use and implementation within wider healthcare; Implement machine learning systems, such as speech recognition and enhanced deep learning/AI; Select learning methods/algorithms and tuning for use in healthcare; Recognize and prepare for the future of artificial intelligence in healthcare through best practices, feedback loops and intelligent agents.','148423796','2019-5-4','Apress','English','368'),
('Arduino Applied','579000','Neil Cameron','Arduino','Extend the range of your Arduino skills, incorporate the new developments in both hardware and software, and understand how the electronic applications function in everyday life. This project-based book extends the Arduino Uno starter kits and increases knowledge of microcontrollers in electronic applications. Learn how to build complex Arduino projects, break them down into smaller ones, and then enhance them, thereby broadening your understanding of each topic.You`ll use the Arduino Uno in a range of applications such as a blinking LED, route mapping with a mobile GPS system, and uploading information to the internet. You`ll also apply the Arduino Uno to sensors, collecting and displaying information, Bluetooth and wireless communications, digital image captures, route tracking with GPS, controlling motors, color and sound, building robots, and internet access. With Arduino Applied, prior knowledge of electronics is not required, as each topic is described and illustrated with examples using the Arduino Uno. Set up the Arduino Uno and its programming environment; Understand the application of electronics in every day systems; Build projects with a microcontroller and readily available electronic components.','148423998','2019-8-9','Apress','English','552'),
('C++ Concurrency in Action, 2nd Edition','1200000','Anthony Williams','C++','This bestseller has been updated and revised to cover all the latest changes to C++ 14 and 17! C++ Concurrency in Action, 2nd Edition teaches you everything you need to write robust and elegant multithreaded applications in C++17. You choose C++ when your applications need to run fast. Well-designed concurrency makes them go even faster. C++ 17 delivers strong support for the multithreaded, multiprocessor programming required for fast graphic processing, machine learning, and other performance-sensitive tasks. This exceptional book unpacks the features, patterns, and best practices of production-grade C++ concurrency. C++ Concurrency in Action, 2nd Edition is the definitive guide to writing elegant multithreaded applications in C++. Updated for C++ 17, it carefully addresses every aspect of concurrent development, from starting new threads to designing fully functional multithreaded algorithms and data structures. Concurrency master Anthony Williams presents examples and practical tasks in every chapter, including insights that will delight even the most experienced developer.','161724691','2019-07-15','Manning','English','592'),
('Sách Thiên Cơ','78734','Túng Mã Càn Khôn','Văn học','Một cuốn sách cổ ngàn năm, tiết lộ về một chức nghiệp thần bí rất đỗi cổ xưa, được các đời hoàng đế vô cùng trọng vọng, song đã tuyệt tích trong dân gian - Thiên Cơ đại phu. Trong cuộc cách mạng Văn hóa thảm khốc, nhân vật chính của cuốn sách, Kỳ Thiên Hạ, đã vô tình tìm thấy cuốn sách này. Nhờ vốn cổ văn có được từ người cha trí thức đã bị tù đày, Kỳ Thiên Hạ bắt tay vào khám phá cổ thư, dấn thân vào những chuyến thám hiểm đầy bất trắc, tiếp nối hành trình của các thế hệ Thiên Cơ đại phu, tìm kiếm bí mật về hào thứ tư đã biến mất từ thiên cổ...','251060782','2015-03-01','Nhà Xuất Bản Văn Học','Tiếng Việt','532'),
('Linux All-In-One For Dummies, 6th Edition','54000','Emmett Dulaney','Linux','Inside, over 800 pages of Linux topics are organized into eight task-oriented mini books that help you understand all aspects of the latest OS distributions of the most popular open-source operating system in use today. Topics include getting up and running with basics, desktops, networking, internet services, administration, security, scripting, Linux certification, and more. This new edition of Linux All-in-One For Dummies has a unique focus on Ubuntu, while still including coverage of Debian, Red Hat, SuSE, and others. The market is looking for administrators, and part of the qualifications needed for job openings is the authentication of skills by vendor-neutral third parties (CompTIA/Linux Professional Institute) - and that`s something other books out there don`t address. Install and configure peripherals, software packages, and keep everything current; Connect to the internet, set up a local area network (including a primer on TCP/IP, and managing a local area network using configuration tools and files); Browse the web securely and anonymously; Get everything you need to pass your entry-level Linux certification exams.','250360782','2018-03-04','Wiley','English','560'),
('Người Đầu Tiên Trong Danh Sách','78400','Magdalena Witkiewicz','Văn học','MagdalenaWitkiewicz- tác giả các cuốn sách đã in tại Nhà xuất bản Trẻ: Trường học dành cho các bà vợ, Lâu đài cát… hiện vẫn đang là tác giả có sách bán chạy nhất của văn học Ba Lan hiện đại. Tác phẩm mới của chị - Người Đầu Tiên Trong Danh Sách - là một tác phẩm ấm áp, xúc động về tình yêu, tình bạn. Thông điệp của tác phẩm: Không bao giờ là quá muộn để thay đổi một điều gì đó trong cuộc sống. Tình cảm thiêng liêng sẽ đưa con người vượt qua mọi lốc xoáy của số phận "Bạn không thể thay đổi quá khứ, nhưng bạn vẫn còn cơ hội để thay đổi tương lai…"','251961208','2016-10-5','Nhà Xuất Bản Trẻ','Tiếng Việt','360'),
('Đọc Sách, Điểm Sách','32392','Nguyễn Ngọc Sơn','Kĩ năng sống','Đọc sách - đó là bạn đang trải nghiệm. Điểm sách - đó là bạn đang đúc kết trải nghiệm của mình. Người thì dùng nó để lưu giữ những cảm xúc bên trong, cũng có có người dùng nó để biểu đạt ra bên ngoài, khuyến khích người khác tìm đọc và rút tỉa những bài học khôn ngoan cho riêng mình Nhưng không phải, nó lúc nào việc viết bài điểm sách cũng dễ dàng lay động, cuốn hút người khác tìm đọc. Nó phụ thuộc vào mức độ cảm thấu nội dung của bạn lẫn cách bạn truyền tải nó trên mặt giấy. Bạn phải hiểu đối tượng mà bạn muốn giới thiệu là ai, cuốn sách này thật sự giúp ích được gì cho họ. Và một điều quan trọng hơn là năng lực sử dụng ngôn ngữ để khiến bài điểm sách trở nên sinh động và có sức hấp dẫn. Vậy, Làm thể nào để đọc cho dễ hiểu và viết cho thật hay? Review là điểm sách hay giới thiệu sách? Đặt tiêu đề thế nào cho cuốn hút? Các bí quyết để viết một bài review hấp dẫn. Tất cả câu hỏi trên sẽ được trình bày một cách rõ ràng và chi tiết trong Đọc sách - Điểm sách.','212213071','2019-03-7','Nhà Xuất Bản Trẻ','Tiếng Việt','164'),
('Combo Bộ Sách Bitcoin','339349','Mark Gates','Sách kinh tế','Tiền điện tử, với đại diện tiêu biểu nhất là Bitcoin, đang là mối quan tâm hàng đầu của giới tài chính toàn cầu. Khả năng thanh toán bằng tiền điện tử mở ra hàng loạt tiềm năng cho thương mại và thay đổi toàn diện thói quen tiêu dùng của con người. Hạt nhân của công nghệ hứa hẹn rung chuyển thế giới này được gọi là Blockchain. Blockchain được giới công nghệ đánh giá là phát kiến vĩ đại nhất sau khi mạng Internet ra đời. Ứng dụng phổ biến nhất của nó là các loại tiền điện tử nổi tiếng (Bitcoin, Ethereum, Ripple...) đang làm mưa làm gió trên thị trường. Nhưng nghịch lý là, lại rất ít người nắm được bản chất của tiền điện tử và Blockchain. Rốt cuộc, Blockchain là gì? Nó hoạt động như thế nào? Blockchain thật sự là một đột phá trong công nghệ hay chỉ là một trào lưu nhất thời? Blockchain có liên hệ như thế nào với Bitcoin? Liệu Blockchain có nắm giữ tiềm năng thay đổi thế giới?...Thực chất, những bài viết cung cấp thông tin về Blockchain và tiền điện tử không thiếu trên các website hay mạng xã hội, nhưng lại chưa đủ tính bao quát và còn khó tiếp thu. Đó là lý do cuốn sách “BLOCKCHAIN: Bản chất của Blockchain, Bitcoin, tiền điện tử, hợp đồng thông minh và tương lai của tiền tệ” của Mark Gates ra đời. Gates cung cấp một bản tóm lược dễ hiểu nhất, cung cấp nền tảng thiết yếu cho những người mới bắt đầu và cả những ai muốn nghiên cứu sâu hơn về công nghệ Blockchain và tiền điện tử. Đọc cuốn sách này, bạn sẽ hiểu được Blockchain dưới nhiều khía cạnh, trong đó không chỉ có những lời ngợi khen mà còn không thiếu các chỉ trích, bình luận trái chiều.','984436267','2017-7-5','Nhà Xuất Bản Lao Động','Tiếng Việt','452'),
('Kẻ Trộm Sách','99996','Markus Zusak','Văn học','Kẻ trộm sách – tác phẩm của nhà văn Úc Markus Zusak xuất bản năm 2005 đã làm mưa làm gió trên bảng xếp hạng những cuốn sách bán chạy nhất của The New York Times hơn 100 tuần liên tiếp, trở thành một tác phẩm kinh điển, một sự lựa chọn của hệ thống các thư viện trường học của Anh và Mỹ. Kẻ trộm sách khi mới ra đời đã lập tức gây ngạc nhiên cho những cây bút phê bình văn học trên thế giới và làm hàng triệu cặp mắt phải nhòa lệ.','251832329','2017-08-7','Nhà Xuất Bản Hội Nhà Văn','Tiếng Việt','571'),
('Đắc Nhân Tâm','68000','Dale Carnegie','Sách kĩ năng sống','Đắc Nhân Tâm - Được lòng người, là cuốn sách đưa ra các lời khuyên về cách thức cư xử, ứng xử và giao tiếp với mọi người để đạt được thành công trong cuộc sống. Gần 80 năm kể từ khi ra đời, Đắc Nhân Tâm là cuốn sách gối đầu giường của nhiều thế hệ luôn muốn hoàn thiện chính mình để vươn tới một cuộc sống tốt đẹp và thành công.Đắc Nhân Tâm cụ thể và chi tiết với những chỉ dẫn để dẫn đạo người, để gây thiện cảm và dẫn dắt người khác,... những hướng dẫn ấy, qua thời gian, có thể không còn thích hợp trong cuộc sống hiện đại nhưng nếu người đọc có thể cảm và hiểu được những thông điệp tác giả muốn truyền đạt thì việc áp dụng nó vào cuộc sống trở nên dễ dàng và hiệu quả.','243418766','2013-3-4','Nhà Xuất Bản Trẻ','Tiếng Việt','319'),
('Tắt Đèn','29000','Ngô Tất Tố','Văn học','Bắt đầu từ gà gáy một tiếng, trâu bò lục-tục kéo thợ cầy đến đoạn đường phía trong điếm tuần. Mọi ngày, giờ ấy, những con-vật này cũng như những người cổ cầy, vai bừa kia, đã lần lượt đi mò ra ruộng làm việc cho chủ. Hôm nay, vì cổng làng chưa mở, chúng phải chia quãng đứng rải rác ở hai vệ đường, giống như một lũ phu vờ chờ đón những ông quan lớn.Dưới bóng tối của rặng tre um tùm, tiếng trâu thở hì hò, tiếng bò đập đuôi đen đét, sen với tiếng người khạc khúng khắng. Cảnh tượng điếm tuần thình lình hiện ra trong ánh lửa lập lòe của chiếc mồi rơm bị thổi. Cạnh giẫy sào, giáo ngả nghiêng dựng ở giáp tường, một lũ tuần phu lố nhố ngồi trên lớp chiếu quằn quèo. Có người phì phò thổi mồi. Có người ve ve mồi thuốc và chìa tay chờ đón điếu đóm. Có người há miệng ngáp dài. Có người đang hai tay dụi mắt. Cũng có người gối đầu trên cái miệng hiệu sừng trâu, ngảnh mặt vào vách mà ngáy. Cái điếu cày và cái đóm lửa bị năm, sáu người chuyền tay, chiếu đi, chiếu lại độ vài ba vòng, ánh lửa lại tắt, trong điếm chỉ còn tiếng nói chuyện rầm rầm.Gà gáy giục. Trời sáng mờ mờ.','255795353','2014-03-19','Nhà Xuất Bản Hồng Đức','Tiếng Việt','199'),
('Head First Design Patterns: A Brain-Friendly Guide','819000',' Eric Freeman , Bert Bates','Design Patterns','At any given moment, someone struggles with the same software design problems you have. And, chances are, someone else has already solved your problem. This edition of Head First Design Patterns—now updated for Java 8—shows you the tried-and-true, road-tested patterns used by developers to create functional, elegant, reusable, and flexible software. By the time you finish this book, you’ll be able to take advantage of the best design practices and experiences of those who have fought the beast of software design and triumphed.','978057526','2004-10-1','O`Reilly Media','English','694'),
('360 Động Từ Bất Quy Tắc','13000','Thanh Hà','Tiếng Anh','Việc học cách sử dụng và cách chia động từ trong tiếng anh là một thử thách nhưng cũng là một điều thú vị. Ngoài các động từ có quy tắc - với dạng quá khứ và quá khứ phân từ - có cách biến đổi đơn giản là thêm “d” hoặc “ed” vào sau động từ, ta còn có các động từ bất quy tắc gồm 360 động từ thông dụng nhất.  Các động từ được sắp xếp theo thứ tự alphabet và có phiên âm rõ ràng. Các bạn có thể sử dụng để học hoặc tra cứu khi cần.Phần 2 cuốn sách là công thức và cách sử dụng của các thì trong tiếng anh. Phần ý nghĩa của từng thì  được tóm tắt một cách đầy đủ và súc tích nhất để thuận lợi cho việc học tập của các bạn.','239367882','2017-06-8','Nhà Xuất Bản Thế Giới','English','108'),
('Phân Loại & Phương Pháp Giải Toán Tích Phân','32200','Nhiều Tác Giả','Toán học','Tích phân - phương pháp tính tích phân của các hàm số là một trong những nội dung quan trọng trong chương trình toán lớp 12. Phân Loại & Phương Pháp Giải Toán Tích Phân được biên soạn nhằm cung cấp cho học sinh phương pháp giải toán tích phân.Nội dung sách bám sát theo sách giáo khoa mới, chương trình chuẩn và chương trình nâng cao. Nội dung mỗi bài gồm các phần sau:A. Kiến thức cơ bảnB.Phân loại và phương pháp giải các dạng toán.- Phương pháp giải- Bài tập mẫu- Bài tập đề nghị gồm bài tập tự luận và bài tập trắc nghiệm khách quan.Các bài tập trong tập sach này được các tác giả chọn lọc kĩ lưỡng, có tính điển hình. Với các lời giải rõ ràng, dễ hiểu giúp các em học sinh tiếp cận và rèn luyện kĩ năng và phương pháp giải toán tích phân để chuẩn bị tốt cho kì thi học kì, thi tốt nghiệp tuyển sinh vào đại học - cao đẳng.','248653446','2013-02-23','Nhà Xuất Bản Đại Học Quốc Gia Hà Nội','Tiếng Việt','312'),
('ĐẠI VIỆT SỬ KÝ TOÀN THƯ','448500','Nhiều tác giả','Lịch sử','Đại Việt sử ký toàn thư là di sản mẫu mực được xem như là chính sử của dân tộc Việt Nam, bộ "sử cái" để đời sau tham khảo đối chiếu, được các nhà sử học nổi tiếng như Lê Văn Hưu, Phan Phu Tiên, Ngô Sĩ Liên, Phạm Công Trứ, Lê Hy... biên soạn. Bản in này sử dụng bản dịch dựa trên bản Nội các quan bản (1697) được phát hành trọn vẹn vào năm 1998 do Ngô Đức Thọ và Hoàng Văn Lâu, các nhà Hán học hàng đầu Việt Nam biên dịch. Mộc bản chữ Hán cũng được tái dựng và in toàn văn. Ngoài ra, sách còn có một số thông tin chú thích về địa danh theo các đơn vị hành chính hiện tại. Bản tra cứu được biên tập và bổ sung đầy đủ, chính xác hơn. Đó là tổng quan về giá trị cuốn sách, nhưng có lẽ phần hình thức mới là điểm khiến người đọc ngưỡng mộ. Đương nhiên có thể xuất bản khổ nhỏ, nhiều tập để dễ dàng phổ biến đến đại đa số độc giả, nhưng một ấn bản bìa cứng, khổ lớn, in ấn và thiết kế đẹp trang trọng thế này cũng là cần thiết để lưu truyền một bộ sử giá trị, dù phần nhiều người Việt Nam ngày nay không còn có thể đọc được văn bản cổ chữ Hán nữa, nhưng việc in vào sách và đặt vào kệ sách từng nhà như một lời hứa không quên cội nguồn dân tộc. Mong Fahasa luôn cung cấp hàng cuốn này thường xuyên.','896751674','2017-04-30','Nhà Xuất bản Văn Học','Tiếng Việt','1263'),
('Dư Địa Chí ','500000','Nhiều tác giả','Địa lí','tổng Tập Dư Địa Chí Việt Nam là công trình sưu tầm, nghiên cứu, tuyển chọn và giới thiệu nhiều tài liệu quý mang tính tiêu biểu của các tác giả danh tiếng trong lịch sử văn học Việt Nam xưa và nay như :Nguyễn Trãi, Lê Quý Đôn, Phan Huy Chú, Lê Tắc, Ngô Văn Triện, Trương Vĩnh Ký, Vương Duy Trinh, Ngô Vi Liễn, Đào Duy Anh... đồng thời tuyển chọn và giới thiệu nhiều tài liệu liên quan của Quốc sử quán triều Nguyễn. Tất cả gồm 40 tác phẩm tiêu biểu trên địa hạt nghiên cứu địa chí của Việt Nam từ thời Trần vào thế kỷ 13 đến thời hiện đại vào giữa thế kỷ 20.','486652973','1435-09-01','Văn hóa Thông tin','Tiếng Việt','6800'),
('Combo Phương Pháp Học Nhanh Hóa Học Thpt Quốc Gia','152900','Lục Trần,Hạnh Chu','Hóa học','Kì thi đại học yêu cầu lượng kiến thức khổng lồ, đòi hỏi các bạn học sinh lớp 12 không chỉ nắm CHẮC mà còn phải nắm ĐỦ kiến thức. Vì vậy, làm thế nào ôn tập trong mấy tháng ngắn ngủi để có thể nắm trọn được kiến thức là vấn đề cấp thiết đặt ra cho các sĩ tử trước kì thi Quốc Gia. Hiểu được khó khăn của các em, Megabook cho ra đời Phương Pháp Học Nhanh Hóa Học THPT Quốc Gia (Hóa học vô cơ và Hóa học hữu cơ)','782593626','2019-01-18','Nhà Xuất Bản Đại Học Quốc Gia Hà Nội','Tiếng Việt','267'),
('Bates` Guide to Physical Examination and History Taking','1664000','Lynn S.Bickley','Vật lý','Bates’ Guide to Physical Examination and History Taking provides authoritative, step-by-step guidance on performing the patient interview and physical examination, applying clinical reasoning, shared decision-making, and other core assessment skills—all based on a firm understanding of clinical evidence.','469893419','2016-09-09',' LWW; Twelfth, North American edition','English','1064'),
('Clean Code: A Handbook of Agile Software Craftsmanship','897000','Robert C. Martin','Lập trình','Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way.Noted software expert Robert C. Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship . Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it.','978016320','2008-08-11','Prentice Hall','English','464');
select orderId from orders where orderUser = 2 order by orderid  desc limit 1 ;

create table if not exists OrderDetails(
	orderId int(10) not null,
    itemId int not null,
    constraint primary key(orderId,itemId),
    constraint fk_OrderDetails_Orders foreign key(orderId) references Orders(orderId),
    constraint fk_OrderDetails_Items foreign key (itemId) references Items(itemId)
);
select orderId from orders where orderUser = 1 order by orderid desc limit 1;
select * from orders;
select * from users;
select * from orderdetails;
select * from orders where orderUser = 1 order by orderid desc limit 1;
select * from Orderdetails where itemId = 1;

select orderStatus from Orders ord inner join OrderDetails ordl on ord.orderId = ordl.orderId where orderUser = 1;
select ord.orderId, ord.orderDate, it.itemName from orders ord inner join orderDetails ordt on ord.orderId = ordt.orderId inner join Items it on ordt.itemId = it.itemId where ord.orderUser = 1 and ord.orderStatus = 1;
-- insert into orders (orderUser,orderStatus) values(1,0);
-- insert into orderdetails(orderId,itemId) values (1,4);
select orderId from orders order by orderid desc limit 1;
create table if not exists Ratings(
	itemId int ,
    userId int,
    ratingStars tinyint,
    ratingTitle nvarchar(255),
    ratingContent text,
    ratingDate datetime,
    constraint primary key(itemId,userId),
    constraint fk_Ratings_Items foreign key(itemId) references Items(itemId),
    constraint fk_Ratings_Users foreign key(userId) references Users(userId)
    );
-- insert into Ratings values();
select * from Ratings;
ALTER TABLE ratings CHARACTER SET=UTF8 COLLATE=utf8_general_ci;
select * from ratings where itemId = 3;
use EBooksStore;
create user if not exists 'customer'@'localhost' identified by 'cus12345';
grant all on users to 'customer'@'localhost';
grant all on items to 'customer'@'localhost';
grant all on orders to 'customer'@'localhost';
grant all on orderdetails to 'customer'@'localhost';
grant all on ratings to 'customer'@'localhost';
grant lock tables on EBooksStore.* to 'customer'@'localhost';
select ord.orderId as orderId, ord.orderDate, it.itemName , it.itemPrice from 
            orders ord inner join orderDetails ordt on ord.orderId = ordt.orderId 
            inner join Items it on ordt.itemId = it.itemId
             where ord.orderUser = 1 and ord.orderId = 2;